apiVersion: apps/v1
kind: Deployment
metadata:
  name: owasp-juice-shop
  labels:
    app: owasp-juice-shop
spec:
  replicas: 2  # Number of pods
  selector:
    matchLabels:
      app: owasp-juice-shop
  template:
    metadata:
      labels:
        app: owasp-juice-shop
    spec:
      containers:
      - name: owasp-juice-shop
        image: bkimminich/juice-shop:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: "/"
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "/"
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: owasp-juice-shop
  labels:
    app: owasp-juice-shop
spec:
  type: LoadBalancer  # Use LoadBalancer for cloud environments or NodePort for local testing
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: owasp-juice-shop
