---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - name: tic-tac-toe
        image: zx2a17/ttt-app:v1
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: ttt-service
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000